# Generated by Django 5.1.1 on 2024-10-08 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0004_servicoadicional_servico_servicos_adicionais'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servico',
            name='servicos_adicionais',
        ),
        migrations.DeleteModel(
            name='ServicoAdicional',
        ),
    ]
