# Generated by Django 5.1.1 on 2024-10-08 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0005_remove_servico_servicos_adicionais_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(choices=[('MAN', 'Manutenção'), ('REP', 'Reparo'), ('LIM', 'Limpeza')], max_length=50)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
        migrations.RemoveField(
            model_name='servico',
            name='categoria_manutencao',
        ),
        migrations.AddField(
            model_name='servico',
            name='tipo_servico',
            field=models.ManyToManyField(to='servicos.tiposervico'),
        ),
        migrations.DeleteModel(
            name='CategoriaManutencao',
        ),
    ]
