# Generated by Django 5.1.1 on 2024-10-08 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0006_tiposervico_remove_servico_categoria_manutencao_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servico',
            name='identificador',
        ),
        migrations.RemoveField(
            model_name='servico',
            name='protocole',
        ),
    ]
