# Generated by Django 5.1.1 on 2024-10-08 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0008_servico_imagem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servico',
            name='imagem',
        ),
    ]
