# Generated by Django 5.1.1 on 2024-10-08 14:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0005_alter_carro_ano_alter_carro_placa_and_more'),
        ('servicos', '0009_remove_servico_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servico',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.cliente'),
        ),
        migrations.AlterField(
            model_name='servico',
            name='data_entrega',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='servico',
            name='data_inicio',
            field=models.DateField(blank=True, null=True),
        ),
    ]
