# Generated by Django 5.1.1 on 2024-10-08 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_agendamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='carro',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='servicos/'),
        ),
    ]
